name: Generate Docs

on:
  pull_request:
    branches: [ "main" ]
    types: ["closed"]

jobs:
  gen-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run doc
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        add-paths: doc/*
        commit-message: "Create pull request for generated documentation"
        commiter: "Aris Kemper <aris.github@gmail.com"
        branch: create-pull-request/gen-docs
        title: "Generated documentation"
    - name: Enable pull request auto merge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.PAT }}
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: squash
